### ISSUE TITLE
snapshot_download failed to finish the download

### ISSUE THREAD

**Issue by rkuo2000** [damo-vilab/i2vgen-xl#18]
while running snapshot_download, I got the following message :
FileIntegrityError: File models/temp/tmpsutrl900/open_clip_pytorch_model.bin integrity check failed, the download may be incomplete, please try again.

**Comment by Steven-SWZhang** [comment]
Sorry, you can also try downloading the model from huggingface.

**Comment by Steven-SWZhang** [comment]
Sorry, you can also try downloading the model from huggingface. https://huggingface.co/damo-vilab/i2vgen-xl/tree/main

**Comment by rkuo2000** [comment]
Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-czivxre0/xformers_7086c53cf88245278df395b02f3003ea/setup.py", line 239, in <module>
          ext_modules=get_extensions(),
        File "/tmp/pip-install-czivxre0/xformers_7086c53cf88245278df395b02f3003ea/setup.py", line 157, in get_extensions
          raise RuntimeError(
      RuntimeError: CUTLASS submodule not found. Did you forget to run `git submodule update --init --recursive` ?
      [end of output]
