### ISSUE TITLE
xformers install error

### ISSUE THREAD

**Issue by konradre** [damo-vilab/i2vgen-xl#9]
```
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/fd/20/da92c5ee5d20cb34e35a630ecf42a6dcd22523d5cb5adb56a0ffe8d03cfa/xformers-0.0.13.tar.gz (292 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-ogjjnmtc\xformers_a9585bbd2bdc42d49f9afc885802555d\setup.py", line 239, in <module>
          ext_modules=get_extensions(),
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-ogjjnmtc\xformers_a9585bbd2bdc42d49f9afc885802555d\setup.py", line 157, in get_extensions
          raise RuntimeError(
      RuntimeError: CUTLASS submodule not found. Did you forget to run `git submodule update --init --recursive` ?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Error persists even after running `git submodule update --init --recursive` in the directory.

**Comment by konradre** [comment]
Issue resolved by changing version from .13 in requirements.txt to .12 as per: https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/2047

Now another error comes:

```
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/26/65/b6eae8046756a24d94c0be3b3375153ca15a7fc0708ae859d852e9e53d84/simplejson-3.18.4-cp38-cp38-win_amd64.whl (74 kB)
ERROR: Could not find a version that satisfies the requirement motion-vector-extractor (from versions: none)
ERROR: No matching distribution found for motion-vector-extractor
```

**Comment by akhilsabu45** [comment]
can you pl help in understanding cuda & python version that needs to be installed, im using win 11, facing same issue as you mentioned

**Comment by VictorLaskin** [comment]
You need to put large disclaimer that windows is unsupported if it is so - so people would not waste their time trying to run it on win 11, please. As I see - motion-vector-extractor - is linux only.

**Comment by VictorLaskin** [comment]
I managed to run it under win11 - 1) in requirements -  xformers==0.0.16 and comment out motion-vector-extractor and triton
2) used slightly different version torch - pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu117
3) reinstalled pip install flash-attn==0.2.1 -i https://pypi.tuna.tsinghua.edu.cn/simple - not sure that it's necessity 
4) changed backend to gloo in i2vgen-xl\tools\inferences\inference_i2vgen_entrance.py(line 82): dist.init_process_group(backend='gloo', world_size=cfg.world_size, rank=cfg.rank)

and it's generating videos while producing some errors like - 'rm' is not recognized as an internal or external command,
operable program or batch file.
'rm' is not recognized as an internal or external command,
operable program or batch file.

**Comment by AlexanderDaly** [comment]
@VictorLaskin Has anyone tried to run this using WSL?..

**Comment by leomaxwell973** [comment]
To resolve the "rm" errors, you can use either Visual Studio(maybe coder too), or Notepad++, and do a folder or project wide replace command using the advanced find functions in each (ctrl+shift+f in VS, ctrl+f in ++):

Find:
rm -rf
Replace:
RD /S /Q

This should translate the unix command to win equivalent so it can perform it's function in a windows environment.

there is always some risk when doing a mass blind multi file line replace batch job, however, "rm -rf" is rather specific so the risk is low IMO, but, you still own your risk and do so at your own risk.

I believe mine said the project had a total of 17 occurrences. no idea where, so, if you knew where though it's not totally undoable manually as well. or you could search for them instead of replace as well, just slower.

**Comment by rlrahulkanojia** [comment]
Make sure you are using python3.8 for installing xformers.
